Repository ticketraider/TicketRadar, pull requests merged in 2024-03, with the labels that each got.

#47 #13 Feat : EventServiceImpl 구현
  src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/Event.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/CustomEventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/price/PriceRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/seat/AvailableSeatRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
Labels: feature

#50 Fix: updateProfile 호출 시 password 암호화 되지 않는 문제 수정
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt
Labels: hotfix

#51 Refactor: Ticket Entity, dto 수정, TicketStatus 추가
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/dto/TicketResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/Ticket.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/TicketStatus.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
Labels: enhancement

#52 Feature/redis lock
  build.gradle.kts
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/Event.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/price/Price.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/seat/AvailableSeats.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/controller/LikeController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/dto/LikeResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/model/Like.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/service/LikeService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/service/LikeServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/PlaceResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/model/Place.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/dto/CreateReviewRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/dto/ReviewResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/model/Review.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/repository/CustomReviewRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/dto/CreateTicketRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/Ticket.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/common/aop/redis/lock/PubSubLock.kt
  src/main/kotlin/com/codersgate/ticketraider/global/common/aop/redis/lock/PubSubLockAspect.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/RedisConfig.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/lock/RedissonLockService.kt
  src/main/resources/application.yml
  src/test/kotlin/com/codersgate/ticketraider/domain/member/repository/MemberRepositoryTest.kt
  src/test/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImplTest.kt
Labels: feature

#54 #53 Feat : Place, Seat 일부 수정, 추가
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/seat/AvailableSeats.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/seat/AvailableSeatRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/CreatePlaceRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/UpdatePlaceResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/model/Place.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceServiceImpl.kt
Labels: feature

#57 #56 Feat : EventServiceImpl findByPageable 수정
  src/main/kotlin/com/codersgate/ticketraider/domain/category/controller/CategoryController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/Status.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/CustomEventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceServiceImpl.kt
Labels: hotfix

#58 Feature/redis cache serialize Feature : 캐시 키 검색 오류 수정
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/CustomEventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/RedisConfig.kt
Labels: feature

#63 #62 Feat : Event, Category CRUD 수정
  src/main/kotlin/com/codersgate/ticketraider/domain/category/repository/CategoryRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/service/CategoryServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/Ticket.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepository.kt
Labels: feature

#64 #60 Feature/ticket 티켓 생성 검사 과정 구현
  src/main/kotlin/com/codersgate/ticketraider/domain/like/controller/LikeController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/dto/CreateTicketRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/dto/TicketResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/Ticket.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/TicketStatus.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
Labels: feature

#67 #62 Fix/event
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/seat/AvailableSeatRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/controller/PlaceController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/CreatePlaceRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/PlaceRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/UpdatePlaceResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/CustomTicketRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepositoryImpl.kt
Labels: feature

#66 Google 소셜 로그인 구현
  src/main/kotlin/com/codersgate/ticketraider/domain/oauth/dto/OAuth2UserInfo.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/oauth/entity/SocialMember.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/oauth/service/OAuth2UserService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/oauth/service/SocialMemberService.kt
  src/main/resources/application.yml
Labels: feature

#70 #feat : likecount , reviewcount 기준으로 조회 기능 추가
  src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/Event.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/CustomEventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepositoryImpl.kt
Labels: feature

#69 Place 별 이벤트 리스트 조회 추가 #62
  src/main/kotlin/com/codersgate/ticketraider/domain/place/controller/PlaceController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/repository/PlaceRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/CustomTicketRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
Labels: feature

#71 #62 Refactor : updateEvent, updatePlace 코드 간략화
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/seat/Bookable.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/CustomEventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/PlaceRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/repository/PlaceRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceServiceImpl.kt
Labels: feature

#72 #60 Feature/ticket 티켓 생성 과정 리팩토링
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/seat/AvailableSeats.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
Labels: enhancement

#75 멤버, 소셜멤버 통합
  src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/dto/OAuth2UserInfo.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/dto/UpdateProfileRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/MemberRole.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/ProviderMap.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/repository/ProviderMapRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/OAuth2LoginSuccessHandler.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/OAuth2UserService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/oauth/entity/SocialMember.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/oauth/repository/SocialMemberRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/oauth/service/SocialMemberService.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/security/SecurityConfig.kt
Labels: feature

#77 Fix/event
  src/main/kotlin/com/codersgate/ticketraider/domain/category/controller/CategoryController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/Event.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/common/aop/redis/lock/PubSubLockAspect.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/TicketReservationFailedException.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/lock/RedissonLockService.kt
  src/main/resources/application.yml
  src/test/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImplTest.kt
Labels: feature, hotfix

#78 #76 Feature : Vue.js 초기 셋팅.
  frontend/.gitignore
  frontend/README.md
  frontend/babel.config.js
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.vue
  frontend/src/assets/logo.png
  frontend/src/components/HelloWorld.vue
  frontend/src/main.js
  frontend/vue.config.js
  src/main/resources/application.yml
Labels: feature

#80 Feature/member rejoin
  src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/ProviderMap.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/repository/ProviderMapRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/security/SecurityConfig.kt
Labels: feature

#84 Feature/member refactor
  src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/OAuth2LoginSuccessHandler.kt
Labels: hotfix

#86 #48, #60 Feature/cache service 캐싱 서비스 구현, CreateTicket 메서드에 적용
  frontend/.gitignore
  frontend/README.md
  frontend/babel.config.js
  frontend/jsconfig.json
  frontend/public/favicon.ico
  frontend/src/assets/logo.png
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/RedisConfig.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/CacheTarget.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheController.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheService.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/security/SecurityConfig.kt
  src/main/resources/application.yml
Labels: feature

#90 #76 Feature/vuetify
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/assets/ticketRadar.png
  frontend/src/components/HeaderView.vue
  frontend/src/components/TicketingViewVer3.vue
  frontend/src/components/trash/SelectSeatStepper.vue
  frontend/src/components/trash/TicketingView.vue
  frontend/src/components/trash/TicketingViewVer2.vue
  frontend/src/css/styles/TestStyle.css
  frontend/src/main.js
  frontend/src/router/router.js
  frontend/src/views/BackOffice.vue
  frontend/src/views/Event.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/MyTicketList.vue
  frontend/src/views/SignUpView.vue
Labels: feature

#97 #76 Feature/vue/back office 백오피스 페이지 구현 완료
  frontend/src/components/BackOffice/CategoryCreateForm.vue
  frontend/src/components/BackOffice/CategoryDeleteForm.vue
  frontend/src/components/BackOffice/CategoryForm.vue
  frontend/src/components/BackOffice/CategoryUpdateForm.vue
  frontend/src/components/BackOffice/EventCreateForm.vue
  frontend/src/components/BackOffice/EventDeleteForm.vue
  frontend/src/components/BackOffice/EventForm.vue
  frontend/src/components/BackOffice/EventUpdateForm.vue
  frontend/src/components/BackOffice/PlaceCreateForm.vue
  frontend/src/components/BackOffice/PlaceDeleteForm.vue
  frontend/src/components/BackOffice/PlaceForm.vue
  frontend/src/components/BackOffice/PlaceUpdateForm.vue
  frontend/src/components/EventCardBack.vue
  frontend/src/main.js
  frontend/src/router/router.js
  frontend/src/views/BackOffice.vue
  frontend/src/views/BackOfficeBack.vue
  frontend/src/views/BackOfficeFront.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/SignUpView.vue
  src/main/kotlin/com/codersgate/ticketraider/domain/category/service/CategoryServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
Labels: feature

#96 #48 Feature/cache service 인기 검색어(이벤트) 기능 구현
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/RedisConfig.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheController.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheService.kt
Labels: feature

#99 #76 Feat : 검색기능 구현 완료
  frontend/src/App.vue
  frontend/src/components/EventListBack.vue
  frontend/src/components/EventListComponent.vue
  frontend/src/components/HeaderComponentVer3.vue
  src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/CustomEventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
Labels: feature

#102 #76 Faet : 티켓목록 조회 css 완료, 티켓 리스폰스에 이벤트아이디 추가
  frontend/src/components/mypage/MyTicketListComponentVer2.vue
  frontend/src/views/MyPageView.vue
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/dto/TicketResponse.kt
Labels: feature

#101 #76 Feature/vue 홈 뷰 이벤트 리스트 작업 완료
  frontend/src/components/EventCardBack.vue
  frontend/src/components/EventCardFront.vue
  frontend/src/components/EventListBack.vue
  frontend/src/components/EventListComponent.vue
  frontend/src/components/HelloWorld.vue
  frontend/src/main.js
  frontend/src/router/router.js
  frontend/src/views/EventDetailView.vue
  frontend/src/views/EventListView.vue
  frontend/src/views/HomeView.vue
  frontend/src/views/HomeViewFront_Backup.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/MyTicketListViewBack.vue
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheController.kt
Labels: feature

#105 #48 Feature/popularity caching 홈뷰 캐싱 리스트 구현 완료
  frontend/src/App.vue
  frontend/src/components/EventDetailComponentFront.vue
  frontend/src/components/EventListComponent.vue
  frontend/src/components/HeaderComponent.vue
  frontend/src/components/HeaderComponentVer2.vue
  frontend/src/views/SignUpView.vue
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/RedisConfig.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheController.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheService.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/SearchEvent.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/SearchEventAspect.kt
Labels: feature

#107 #76 Feature/event crud fix 이벤트 생성/수정 구현 완료
  frontend/src/components/BackOffice/EventCreateForm.vue
  frontend/src/components/BackOffice/EventUpdateForm.vue
  src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/service/LikeServiceImpl.kt
Labels: feature

#109 #76 Feature/view refectoring 뷰 스타일 작업 진행중
  build.gradle.kts
  frontend/src/assets/ticketRadar_logo.png
  frontend/src/components/EventDetailComponentFront.vue
  frontend/src/components/EventListComponent.vue
  frontend/src/components/HeaderComponent.vue
  frontend/src/css/styles/TestStyle.css
  frontend/src/views/EventDetailView.vue
  frontend/src/views/EventListView.vue
  frontend/src/views/HomeView.vue
  frontend/src/views/HomeViewFront_Backup.vue
  frontend/src/views/LoginView.vue
Labels: feature

#111 Feature/img upload
  src/main/kotlin/com/codersgate/ticketraider/global/infra/s3/S3Service.kt
  src/main/resources/application.yml
Labels: feature
