Repository ticketraider/TicketRadar, pull requests merged in 2024-04, with the labels that each got.

#118 #48 Feat : 캐시 리스트 스케쥴링 재적용 ( 서버 최초 실행시 호출, 이후 30분 마다 실행 되도록 )
  frontend/src/components/EventListComponent.vue
  frontend/src/views/HomeView.vue
  src/main/kotlin/com/codersgate/ticketraider/TicketRaiderApplication.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheService.kt
Labels: feature

#119 Feature/front back
  frontend/src/components/mypage/MyTicketListComponent.vue
  frontend/src/components/mypage/MyTicketListComponentVer2.vue
  frontend/src/components/mypage/UserInfoComponent.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/SignUpView.vue
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/common/aop/redis/lock/PubSubLockAspect.kt
  src/main/resources/application.yml
  src/test/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImplTest.kt
Labels: hotfix

#122 #48 Feat/pop search 인기 검색어 실시간 반영
  frontend/src/components/HeaderComponent.vue
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/PopKeywords/PopKeyword.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/PopKeywords/PopKeywordRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/PopKeywords/PopKeywordService.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheController.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheService.kt
Labels: feature

#126 #76 뷰 리스타일링 작업 완료 , API 연결
  frontend/src/App.vue
  frontend/src/components/EventDetailComponentFront.vue
  frontend/src/components/HeaderComponent.vue
  frontend/src/components/ReviewListComponent.vue
  frontend/src/components/TicketViewerBack.vue
  frontend/src/components/TicketingComponent.vue
  frontend/src/components/TicketingComponentVer4Front.vue
  frontend/src/components/mypage/MyLikeListComponent.vue
  frontend/src/components/mypage/MyReviewListComponent.vue
  frontend/src/components/mypage/MyTicketListBack.vue
  frontend/src/components/mypage/MyTicketListComponent.vue
  frontend/src/components/mypage/UserInfoComponent.vue
  frontend/src/main.js
  frontend/src/router/router.js
  frontend/src/views/EventDetailView.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/MyPageView.vue
  frontend/src/views/TicketViewerView.vue
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheService.kt
Labels: enhancement, feature

#133 #130 Fix : 유저 피드백 반영
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/common/BaseEntity.kt
Labels: enhancement

#134 #76 Feat/pop search 뷰 관련 작업
  frontend/src/components/ReviewListComponent.vue
  frontend/src/components/TicketingComponent.vue
  frontend/src/components/mypage/MyTicketListComponent.vue
  frontend/src/components/mypage/UserInfoComponent.vue
  src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/cache/RedisCacheService.kt
Labels: feature
