Repository ticketraider/TicketRadar, pull requests merged in 2024-02, with the labels that each got.

#3 #2 Feat : Category, Infra, Exception, Common 패키지 생성 및 구현
  src/main/kotlin/com/codersgate/ticketraider/TicketRaiderApplication.kt
  src/main/kotlin/com/codersgate/ticketraider/common/BaseEntity.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/controller/CategoryController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/dto/CategoryResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/dto/CreateCategoryRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/dto/UpdateCategoryRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/model/Category.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/repository/CategoryRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/repository/CategoryRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/repository/CustomCategoryRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/service/CategoryService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/service/CategoryServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/codersgate/ticketraider/error/exception/AccessDeniedException.kt
  src/main/kotlin/com/codersgate/ticketraider/error/exception/EmailAlreadyExistException.kt
  src/main/kotlin/com/codersgate/ticketraider/error/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/codersgate/ticketraider/error/exception/ModelNotFoundException.kt
  src/main/kotlin/com/codersgate/ticketraider/error/exception/dto/BaseResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/error/exception/dto/ErrorResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/error/exception/status/ResultCode.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/querydsl/QueryDslSupport.kt
Labels: feature

#5 #2 Feat : SwaggerConfig 생성
  src/main/kotlin/com/codersgate/ticketraider/domain/category/model/Category.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/repository/CategoryRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/category/service/CategoryServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/error/exception/dto/ErrorResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/global/common/BaseEntity.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/AccessDeniedException.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/EmailAlreadyExistException.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/ModelNotFoundException.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/dto/BaseResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/dto/ErrorResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/status/ResultCode.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/querydsl/QueryDslSupport.kt
  src/main/kotlin/com/codersgate/ticketraider/global/infra/swagger/SwaggerConfig.kt
Labels: feature

#7 #6 Feat : Place 패키지 생성 및 구현
  src/main/kotlin/com/codersgate/ticketraider/domain/place/controller/PlaceController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/CreatePlaceRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/PlaceResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/UpdatePlaceResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/model/Place.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/repository/PlaceRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceServiceImpl.kt
Labels: feature

#12 Fix/securityconfig
  src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/dto/LoginRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/dto/LoginResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/dto/MemberRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/dto/MemberResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/MemberRole.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/InvalidCredentialException.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/PasswordEncoderConfig.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/SecurityConfig.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/UserPrincipal.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/jwt/JwtPlugin.kt
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: bug

#10 Feat: Member 패키지 CRUD, JWT 토큰 파일 생성
  src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/dto/LoginRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/dto/LoginResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/dto/MemberRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/dto/MemberResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/MemberRole.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/codersgate/ticketraider/global/error/exception/InvalidCredentialException.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/PasswordEncoderConfig.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/SecurityConfig.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/UserPrincipal.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/com/codersgate/ticketraider/infra/security/jwt/JwtPlugin.kt
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feature

#9 Feature/review Review CRUD 완성
  src/main/kotlin/com/codersgate/ticketraider/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/dto/CreateReviewRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/dto/ReviewResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/dto/UpdateReviewRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/model/Review.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/repository/CustomReviewRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/repository/CustomReviewRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/repository/ReviewRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt
Labels: feature

#16 Fix: Enumerated 타입 오류 수정
  src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt
Labels: bug

#21 #20 hotfix : Review controller 경로 설정 실수 수정
  src/main/kotlin/com/codersgate/ticketraider/domain/like/controller/LikeController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/model/Like.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt
Labels: hotfix

#22 #19 Feat : Event 기능 구현
  src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/CreateEventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/UpdateEventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/Bookable.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/Event.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
Labels: feature

#25 Fix: MemberRole enum User->Member로 변경
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/MemberRole.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt
Labels: bug

#27 #14 Feature/like 구현 완료 ( 테스트 필요 )
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/controller/LikeController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/dto/LikeResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/model/Like.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/CustomLikeRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/CustomLikeRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/LikeRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/service/LikeService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/service/LikeServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/dto/CreateReviewRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/model/Review.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt
Labels: feature

#32 Feat: Ticket Package 추가
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/dto/CreateTicketRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/dto/TicketResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/Ticket.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/TicketGrade.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/CustomTicketRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
Labels: feature

#28 #4 Feature/review Member, Event 내용 반영
  src/main/kotlin/com/codersgate/ticketraider/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/dto/ReviewResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/repository/CustomReviewRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/repository/CustomReviewRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt
Labels: feature

#30 #29 Fix/set h2
  src/main/kotlin/com/codersgate/ticketraider/global/infra/security/SecurityConfig.kt
  src/main/resources/application.yml
Labels: hotfix

#34 Fix: Member Package 연관관계 수정, @valid 어노테이션 빠진 거 수정
  src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
Labels: bug

#37 Feature/event price&seat
  src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/CreateEventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/UpdateEventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/price/CreatePriceRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/price/PriceResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/price/UpdatePriceRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/seat/CreateSeatRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/seat/SeatResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/seat/UpdateSeatRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/Event.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/price/Price.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/seat/Bookable.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/seat/Seat.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/price/PriceRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/seat/SeatRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/repository/PlaceRepository.kt
Labels: feature

#40 #14 Feature/like count 기능 구현 / 테스트 완료
  src/main/kotlin/com/codersgate/ticketraider/domain/like/controller/LikeController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/CustomLikeRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/CustomLikeRepositoryImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/LikeRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/service/LikeService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/like/service/LikeServiceImpl.kt
Labels: feature

#42 Fix: Member 패키지 오류 수정
  src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/dto/MemberResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt
Labels: bug

#44 #4 Fix : @SQLDelete, @Transactional 설정, UpdateRequest 항목 수정
  src/main/kotlin/com/codersgate/ticketraider/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/dto/UpdateReviewRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/review/model/Review.kt
Labels: hotfix

#45 Feature/event price&seat
  src/main/kotlin/com/codersgate/ticketraider/domain/category/model/Category.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/CreateEventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/UpdateEventRequest.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/seat/SeatResponse.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/Event.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/price/Price.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/model/seat/AvailableSeats.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/seat/SeatRepository.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventService.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
  src/main/kotlin/com/codersgate/ticketraider/domain/place/model/Place.kt
Labels: feature
